### ISSUE TITLE
Please make sure you have virtual environment set up

### ISSUE THREAD

**Issue by ggnjt** [Citram/MyCampus-Backend#1]
Setting up a virtual environment helps to keep the packages you installed on your system separate from the ones needed/used for the website.
Try the following commands in the folder containing manage.py file (make sure you have pip installed):
pip install virtualenv
virtualenv --version (should show you the version)
virtualenv env
pip freeze (should be empty)
pip install django (and other packages)

**Comment by ImaneChafi** [comment]
Also, make sure you have ` python3`  running and not ` python2`  when you try out the app, or else you'll get an error for syntax like this when you try to run it 
`  File "manage.py", line 16
    ) from exc
         ^
SyntaxError: invalid syntax
`

**Comment by ggnjt** [comment]
Python 2 is no more
